### ISSUE TITLE
Nuance to EnumValueAdded's criticality

### ISSUE THREAD

**Issue by cjoudrey** [xuorig/graphql-schema_comparator#18]
At the moment, all `EnumValueAdded` changes are marked as `dangerous` because it may break clients that do not handle a certain enum value.

This is true if you're using the enum as a field type, but if you're only using it as an argument type, adding a new enum value _should_ be safe.

**Comment by jturkel** [comment]
Similarly should removing an enum value for enums only used in field types and not argument types be safe? In that case, the enum value should never appear in a client request so I don't think it could break anything.
