### ISSUE TITLE
CC BY 4.0 License

### ISSUE THREAD

**Issue by tesoy-xx** [xuorig/graphql-schema_comparator#26]
https://github.com/xuorig/graphql-schema_comparator/blob/e3bab4dc1dc6cbe216fcf93b73385afb58e0e5a9/lib/graphql/schema_comparator/changes/safe_type_change.rb#L19

**Comment by swalkinshaw** [comment]
Not sure what this issue is about since there's no description? Feel free to re-open with more details.
