### ISSUE TITLE
Don't treat adding a required argument with a default value as a breaking change

### ISSUE THREAD

**Issue by RobertWSaunders** [xuorig/graphql-schema_comparator#34]
## Overview

Right now if an argument is changed from not required to required with a default value it is considered a breaking change. Since the default value guards the case where someone doesn't specify the argument this shouldn't be considered a breaking change.

**Comment by jturkel** [comment]
Won't this be a breaking change for clients that are explicitly passing a null for the now required argument?

**Comment by jturkel** [comment]
#38 made adding a required argument with a default value non-breaking. That still leaves the scenario described in this issue for changing an argument from not required to required with a default argument though.

**Comment by RobertWSaunders** [comment]
> Won't this be a breaking change for clients that are explicitly passing a null for the now required argument?

I would think that if you pass `null` it would still use the default? Do you have an example?

**Comment by jturkel** [comment]
I confirmed the default doesn't apply when passed an explicit `null` with graphql-ruby:

```ruby
require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'
  gem 'graphql'
  gem 'rspec'
  gem 'json_spec'
end

require 'rspec/autorun'

class QueryType < GraphQL::Schema::Object
  field :echo, String, null: true do
    argument :input, String, required: false, default_value: 'hello'
  end

  def echo(input:)
    input
  end
end

class TestSchema < GraphQL::Schema
  query QueryType
end

describe do
  specify do
    query = <<~GRAPHQL
      query {
        echo(input: null)
      }
    GRAPHQL

    result = TestSchema.execute(query)
    expect(result.to_json).to be_json_eql({data: {echo: nil}}.to_json)
  end
end
```
I checked the GraphQL Spec and this seems to be expected behavior according to the [field argument coercion algorithm](https://spec.graphql.org/June2018/#sec-Coercing-Field-Arguments) and the [input object coercion rules](https://spec.graphql.org/draft/#sec-Input-Objects.Input-Coercion).

**Comment by RobertWSaunders** [comment]
Nice, then we can close this, thanks for the detailed example! 💯 👍
