### ISSUE TITLE
Don't treat a non-null input type field changing to nullable input type field as a breaking change

### ISSUE THREAD

**Issue by RobertWSaunders** [xuorig/graphql-schema_comparator#35]
## Overview

If an input type has a field that is non-null and that field is changing to a nullable field, we should not treat that as a breaking change but the gem currently does. It's not a breaking since any clients would already be supplying the input field, with the change they have the opportunity to not do that anymore.

**Comment by jturkel** [comment]
@RobertWSaunders - I couldn't reproduce this problem with the following test case. Do you have a reproducible test case you could share?

```ruby
old_schema_idl = <<~SCHEMA
  schema {
    query: Query
  }
  input Foo {
    bar: String!
  }
  type Query {
    a(foo: Foo!): String!
  }
SCHEMA

new_schema_idl = <<~SCHEMA
  schema {
    query: Query
  }
  input Foo {
    bar: String
  }
  type Query {
    a(foo: Foo!): String!
  }
SCHEMA

result = GraphQL::SchemaComparator.compare(old_schema_idl, new_schema_idl)

assert_equal ["Input field `Foo.bar` changed type from `String!` to `String`"], 
                       result.changes.map(&:message)

refute result.breaking?
```

**Comment by RobertWSaunders** [comment]
Ah weird, maybe it's no longer an issue 👍 We can close this and re-open if it pops up again.
