### ISSUE TITLE
Safe nullability changes are marked unsafe incorrectly

### ISSUE THREAD

**Issue by eapache-opslevel** [xuorig/graphql-schema_comparator#52]
v1.1.1
graphql-ruby v2.0.8

@swalkinshaw 

Possibly a duplicate/confirmation of #35? cc @RobertWSaunders @jturkel 

In the following test case, the change from `bar: Bar!` to `bar: Bar` on an input type gets marked breaking incorrectly:
```ruby
require 'graphql/schema_comparator'

old_schema_idl = <<~SCHEMA
  schema {
    query: Query
  }
  input Foo {
    bar: Bar!
  }
  input Bar {
    x: String
  }
  type Query {
    a(foo: Foo!): String!
  }
SCHEMA

new_schema_idl = <<~SCHEMA
  schema {
    query: Query
  }
  input Foo {
    bar: Bar
  }
  input Bar {
    x: String
  }
  type Query {
    a(foo: Foo!): String!
  }
SCHEMA

result = GraphQL::SchemaComparator.compare(old_schema_idl, new_schema_idl)

puts result.changes.map(&:message)

puts result.breaking?
```

It looks like what's happening is that the parser is generating different classes for schema type `Bar` in the two schemas, so when the straight equality is run at https://github.com/xuorig/graphql-schema_comparator/blob/6a44b0862d4e1461824da287ab266751750321ce/lib/graphql/schema_comparator/changes/safe_type_change.rb#L21 after peeling away the (safe) nullability change, the underlying types come back as different.

I'm not sure how this ever worked, or why we never ran into it at Shopify? Maybe the gem recently change how it parses string schemas to generate duplicate classes?

**Comment by swalkinshaw** [comment]
https://github.com/xuorig/graphql-schema_comparator/blob/6a44b0862d4e1461824da287ab266751750321ce/test/lib/graphql/schema_comparator/diff/input_field_test.rb#L36-L48

This test looks like it should reflect that or is something different?

**Comment by swalkinshaw** [comment]
Ah it's because of how the tests are written 😞 they don't parse actual schemas so they don't run into this issue. https://github.com/xuorig/graphql-schema_comparator/pull/53
